REDASH_DATABASE_URL=postgresql://redash:redash@redash_postgres:5432/redash
REDASH_REDIS_URL=redis://redash_redis:6379/0
REDASH_COOKIE_SECRET=${REDASH_COOKIE_SECRET}
REDASH_SECRET_KEY=${REDASH_SECRET_KEY}
